### PR TITLE
feat(environments): remove DEVELOPMENT environment and point LOCAL to…

### LINKED ISSUE #46: Frontend local environment should point to integration endpoint
We need to remove `dev` from the endpoint list.

### PR DESCRIPTION
**Pull request by dami-gg**
… INTEGRATION urls

Closes #46

### CODE REVIEW

**Comment by cjhowald** [comment]
Please revert dist changes.

**Comment by cjhowald** [comment]
👍

**Comment by dami-gg** [comment]
Done. Apparently running the tests generates the distribution files and does some tests also on them... Perhaps we should change that.

Anyway, in general, I think we should be more flexible with the fact of adding /dist files to PRs, since they don't affect that much, NPM relates to the tags and nobody (apart from us during development) is supposed to be pulling from the master branch (and if they do they shouldn't be able to complain because of troubles related to it)

**Comment by dami-gg** [comment]
:+1:

**Comment by cjhowald** [comment]
👍

**Pull request merged**
