### PR TITLE
feat(services): add new module service URLs

### LINKED ISSUE #27: NPS / Update communicator with endpoint
Need to add the NPS endpoint. See [solution-center-feedback](https://github.com/zalando-incubator/solution-center-feedback/issues?q=is%3Aopen+is%3Aissue+milestone%3A%22Sprint+CW+33+2016%22) for more info.

### PR DESCRIPTION
**Pull request by dami-gg**
Closes #27 

The production environment is not deployed yet but I've already included the URL agreed with Sherif

### CODE REVIEW

**Comment by gregdeane** [comment]
Please revert the `dist` changes.

**Comment by gregdeane** [comment]
Looks good. Unit tests pass. Please revert `dist` before merging.

**Comment by gregdeane** [comment]
👍

**Comment by dami-gg** [comment]
Need thumbs up again @gregdeane  ;)

**Comment by dami-gg** [comment]
:+1:

**Comment by gregdeane** [comment]
👍

**Pull request merged**
